@startuml tehtava2

object Peli
object Noppa
object Pelaaja {
    rahamaara: int
}
object Pelinappula
object Lauta
interface Ruutu 
object Aloitusruutu
object Vankila
object Sattuma
object Yhteismaa
object Asema
object Laitos
object Katu {
    nimi: String
}
interface Toiminto
object Kortti
interface Rakennus
object Talo
object Hotelli

Peli "1" -- "2" Noppa
Peli "1" -- "2..8" Pelaaja
Peli "1" -- "1" Lauta
Peli "1" -- "1" Aloitusruutu
Peli "1" -- "1" Vankila
Pelaaja "1" -- "1" Pelinappula
Lauta "1" -- "40" Ruutu
Ruutu "1" -- "1" Ruutu
Ruutu "1" -- "1" Toiminto
Sattuma "1" -- "*" Kortti
Yhteismaa "1" -- "*" Kortti
Kortti "1" -- "1" Toiminto
Pelinappula "0..8" -- "1" Ruutu
Katu "*" -- "0..1" Pelaaja
Aloitusruutu -> Ruutu
Vankila -> Ruutu
Sattuma -> Ruutu
Yhteismaa -> Ruutu
Asema -> Ruutu
Laitos -> Ruutu
Katu -> Ruutu
Talo -> Rakennus
Hotelli -> Rakennus
Hotelli "0..1" -- Katu
Talo "0..4" -- Katu
Rakennus "0..4" -- Katu

@enduml